AWSTemplateFormatVersion: "2010-09-09"
Description: Ec2 sample Webserver
Resources:
  MyEC2Instance:
    Type: "AWS::EC2::Instance"
    Properties: 
      ImageId: "ami-02f3f602d23f1659d"
      InstanceType: t2.micro      
      BlockDeviceMappings:
        -
          DeviceName: /dev/xvda
          Ebs:
            VolumeType: gp2            
            DeleteOnTermination: true
            VolumeSize: 8
            